select t.table_name, C.COLUMN_NAME,t.CONSTRAINT_TYPE FROM  
INFORMATION_SCHEMA.TABLE_CONSTRAINTS T  
JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE C  
ON C.CONSTRAINT_NAME=T.CONSTRAINT_NAME  
WHERE  
--C.TABLE_NAME='Employee'  and 
T.CONSTRAINT_TYPE='PRIMARY KEY' 